/// Embedded error code database derived from CMTrace binary analysis.
/// Contains common Windows, SCCM, Intune, and Windows Update error codes.
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ErrorCategory {
    Windows,
    WindowsUpdate,
    Bits,
    ConfigMgr,
    Intune,
    DeliveryOpt,
    AppInstall,
    Certificate,
    Network,
    Security,
    Registry,
    FileSystem,
}

impl ErrorCategory {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Windows => "Windows",
            Self::WindowsUpdate => "Windows Update",
            Self::Bits => "BITS",
            Self::ConfigMgr => "ConfigMgr",
            Self::Intune => "Intune",
            Self::DeliveryOpt => "Delivery Optimization",
            Self::AppInstall => "App Install",
            Self::Certificate => "Certificate",
            Self::Network => "Network",
            Self::Security => "Security",
            Self::Registry => "Registry",
            Self::FileSystem => "File System",
        }
    }
}

#[derive(Debug, Clone)]
pub struct ErrorCode {
    pub code: u32,
    pub description: &'static str,
    pub category: ErrorCategory,
}

pub static ERROR_CODES: &[ErrorCode] = &[
    // ==========================================
    // Windows / HRESULT errors
    // ==========================================
    ErrorCode { code: 0x00000000, description: "S_OK - The operation completed successfully", category: ErrorCategory::Windows },
    ErrorCode { code: 0x00000001, description: "S_FALSE - The operation completed with a non-critical warning", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004001, description: "E_NOTIMPL - Not implemented", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004002, description: "E_NOINTERFACE - No such interface supported", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004003, description: "E_POINTER - Invalid pointer", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004004, description: "E_ABORT - Operation aborted", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004005, description: "E_FAIL - Unspecified failure", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004006, description: "CO_E_INIT_TLS - Thread local storage failure", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004015, description: "CO_E_WRONGOSFORAPP - Application not found", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8000FFFF, description: "E_UNEXPECTED - Unexpected failure", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80010105, description: "RPC_E_SERVERFAULT - The server threw an exception", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80010108, description: "RPC_E_DISCONNECTED - The object invoked has disconnected from its clients", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8001010D, description: "RPC_E_SERVERFAULT - The server threw an exception", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800401F0, description: "CO_E_NOTINITIALIZED - COM not initialized", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80040154, description: "REGDB_E_CLASSNOTREG - Class not registered", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80040201, description: "CACHE_E_NOCACHE_UPDATED - No cache updated", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070001, description: "ERROR_INVALID_FUNCTION - Incorrect function", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070002, description: "ERROR_FILE_NOT_FOUND - The system cannot find the file specified", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070003, description: "ERROR_PATH_NOT_FOUND - The system cannot find the path specified", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070004, description: "ERROR_TOO_MANY_OPEN_FILES - The system cannot open the file", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070005, description: "E_ACCESSDENIED - Access is denied", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070006, description: "ERROR_INVALID_HANDLE - The handle is invalid", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070007, description: "ERROR_ARENA_TRASHED - The storage control blocks were destroyed", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070008, description: "ERROR_NOT_ENOUGH_MEMORY - Not enough storage is available", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007000A, description: "ERROR_BAD_ENVIRONMENT - The environment is incorrect", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007000B, description: "ERROR_BAD_FORMAT - An attempt was made to load a program with an incorrect format", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007000D, description: "ERROR_INVALID_DATA - The data is invalid", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007000E, description: "E_OUTOFMEMORY - Not enough memory resources to complete this operation", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007000F, description: "ERROR_INVALID_DRIVE - The system cannot find the drive specified", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070011, description: "ERROR_NOT_SAME_DEVICE - The system cannot move the file to a different disk drive", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070012, description: "ERROR_NO_MORE_FILES - There are no more files", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070015, description: "ERROR_NOT_READY - The device is not ready", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007001D, description: "ERROR_WRITE_FAULT - The system cannot write to the specified device", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007001E, description: "ERROR_READ_FAULT - The system cannot read from the specified device", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007001F, description: "ERROR_GEN_FAILURE - A device attached to the system is not functioning", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070020, description: "ERROR_SHARING_VIOLATION - The process cannot access the file because it is being used by another process", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070021, description: "ERROR_LOCK_VIOLATION - The process cannot access the file because another process has locked a portion of the file", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070026, description: "ERROR_HANDLE_EOF - Reached the end of the file", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070027, description: "ERROR_HANDLE_DISK_FULL - The disk is full", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070032, description: "ERROR_NOT_SUPPORTED - The request is not supported", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070033, description: "ERROR_REM_NOT_LIST - Windows cannot find the network path", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070035, description: "ERROR_BAD_NETPATH - The network path was not found", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070037, description: "ERROR_DEV_NOT_EXIST - The specified network resource or device is no longer available", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007003B, description: "ERROR_UNEXP_NET_ERR - An unexpected network error occurred", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070040, description: "ERROR_NETNAME_DELETED - The specified network name is no longer available", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070041, description: "ERROR_NETWORK_ACCESS_DENIED - Network access is denied", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070043, description: "ERROR_BAD_NET_NAME - The network name cannot be found", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070050, description: "ERROR_FILE_EXISTS - The file exists", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070052, description: "ERROR_DUP_NAME - Duplicate name on the network", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070056, description: "ERROR_INVALID_PASSWORD - The specified network password is not correct", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070057, description: "E_INVALIDARG - One or more arguments are invalid", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007006D, description: "ERROR_BROKEN_PIPE - The pipe has been ended", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007006E, description: "ERROR_OPEN_FAILED - The system cannot open the device or file specified", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007006F, description: "ERROR_BUFFER_OVERFLOW - The file name is too long", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070070, description: "ERROR_DISK_FULL - There is not enough space on the disk", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070078, description: "ERROR_CALL_NOT_IMPLEMENTED - This function is not supported on this system", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070079, description: "ERROR_SEM_TIMEOUT - The semaphore timeout period has expired", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007007A, description: "ERROR_INSUFFICIENT_BUFFER - The data area passed to a system call is too small", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007007B, description: "ERROR_INVALID_NAME - The filename, directory name, or volume label syntax is incorrect", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007007E, description: "ERROR_MOD_NOT_FOUND - The specified module could not be found", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007007F, description: "ERROR_PROC_NOT_FOUND - The specified procedure could not be found", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070091, description: "ERROR_DIR_NOT_EMPTY - The directory is not empty", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007009E, description: "ERROR_NOT_LOCKED - The segment is already unlocked", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800700A1, description: "ERROR_BAD_PATHNAME - The specified path is invalid", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800700AA, description: "ERROR_BUSY - The requested resource is in use", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800700B7, description: "ERROR_ALREADY_EXISTS - Cannot create a file when that file already exists", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800700C1, description: "ERROR_BAD_EXE_FORMAT - Not a valid Win32 application", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800700CB, description: "ERROR_ENVVAR_NOT_FOUND - The system could not find the environment option that was entered", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800700CE, description: "ERROR_FILENAME_EXCED_RANGE - The file name or extension is too long", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800700E1, description: "ERROR_VIRUS_INFECTED - Operation did not complete successfully because the file contains a virus", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800700EA, description: "ERROR_MORE_DATA - More data is available", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070102, description: "WAIT_TIMEOUT - The wait operation timed out", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070103, description: "NO_MORE_ITEMS - No more data is available", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007010B, description: "ERROR_DIRECTORY - The directory name is invalid", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007013D, description: "ERROR_MR_MID_NOT_FOUND - The system cannot find message text for message number", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007015E, description: "ERROR_FAIL_NOACTION_REBOOT - No action was taken because a system reboot is required", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800701E7, description: "ERROR_INVALID_ADDRESS - Attempt to access invalid address", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800701F4, description: "ERROR_USER_PROFILE_LOAD - User profile cannot be loaded", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070216, description: "ERROR_ARITHMETIC_OVERFLOW - Arithmetic result exceeded 32 bits", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007023C, description: "ERROR_CONTROL_C_EXIT - Application terminated as a result of CTRL+C", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070241, description: "ERROR_INVALID_IMAGE_HASH - The hash for the image cannot be found in the system catalogs", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800702E4, description: "ERROR_ELEVATION_REQUIRED - The requested operation requires elevation", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800703E5, description: "ERROR_IO_PENDING - Overlapped I/O operation is in progress", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800703E6, description: "ERROR_NOACCESS - Invalid access to memory location", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007041D, description: "ERROR_SERVICE_REQUEST_TIMEOUT - The service did not respond to the start or control request in a timely fashion", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070422, description: "ERROR_SERVICE_DISABLED - The service is disabled", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070424, description: "ERROR_SERVICE_DOES_NOT_EXIST - The specified service does not exist", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007042B, description: "ERROR_PROCESS_ABORTED - The process terminated unexpectedly", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007042C, description: "ERROR_SERVICE_DEPENDENCY_FAIL - The dependency service or group failed to start", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007046A, description: "ERROR_NOT_ENOUGH_SERVER_MEMORY - Not enough server storage is available to process this command", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070490, description: "E_ELEMENT_NOT_FOUND - Element not found", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800704C3, description: "ERROR_SESSION_CREDENTIAL_CONFLICT - Multiple connections to a server using more than one user name not allowed", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800704C7, description: "ERROR_CANCELLED - The operation was canceled by the user", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800704CF, description: "ERROR_NETWORK_UNREACHABLE - The network location cannot be reached", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800704DD, description: "ERROR_NOT_LOGGED_ON - The user is not logged on", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800704EC, description: "ERROR_ACCESS_DISABLED_BY_POLICY - This program is blocked by group policy", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070522, description: "ERROR_PRIVILEGE_NOT_HELD - A required privilege is not held by the client", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007052E, description: "ERROR_LOGON_FAILURE - Logon failure: unknown user name or bad password", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070570, description: "ERROR_FILE_CORRUPT - The file or directory is corrupted and unreadable", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070574, description: "ERROR_LOGON_FAILURE_MUTUAL_AUTH - Logon Failure: The target account name is incorrect", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800705B4, description: "ERROR_TIMEOUT - This operation returned because the timeout period expired", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800705DC, description: "ERROR_EVENTLOG_CANT_START - The event log file is corrupted", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070643, description: "ERROR_INSTALL_FAILURE - Fatal error during installation", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070652, description: "ERROR_INSTALL_ALREADY_RUNNING - Another installation is already in progress", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800706BA, description: "RPC_S_SERVER_UNAVAILABLE - The RPC server is unavailable", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800706BE, description: "RPC_S_CALL_FAILED - The remote procedure call failed", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070775, description: "ERROR_INVALID_DATATYPE - The specified data type is invalid", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800706D9, description: "RPC_S_NO_BINDINGS - There are no bindings", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800706BB, description: "RPC_S_SERVER_TOO_BUSY - The RPC server is too busy to complete this operation", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070BC2, description: "ERROR_SUCCESS_REBOOT_REQUIRED - A restart is required to complete the install", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070BC9, description: "ERROR_FAIL_REBOOT_REQUIRED - A restart is required to complete the uninstall", category: ErrorCategory::Windows },

    // ==========================================
    // Windows Update Agent
    // ==========================================
    // WUA success codes
    ErrorCode { code: 0x00240001, description: "WU_S_SERVICE_STOP - Windows Update Agent was stopped successfully", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x00240002, description: "WU_S_SELFUPDATE - Windows Update Agent updated itself", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x00240005, description: "WU_S_REBOOT_REQUIRED - The system needs to be rebooted to complete installation", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x00240006, description: "WU_S_ALREADY_INSTALLED - The update to be installed is already installed", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x00240008, description: "WU_S_ALREADY_DOWNLOADED - The update to be downloaded has already been downloaded", category: ErrorCategory::WindowsUpdate },
    // WUA error codes
    ErrorCode { code: 0x80240001, description: "WU_E_NO_SERVICE - Windows Update Agent was unable to provide the service", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240002, description: "WU_E_MAX_CAPACITY_REACHED - Maximum capacity of the service was exceeded", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240003, description: "WU_E_UNKNOWN_ID - An ID that was not recognized", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240004, description: "WU_E_NOT_INITIALIZED - The object could not be initialized", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240005, description: "WU_E_RANGEOVERLAP - The update handler requested a byte range overlapping a previously requested range", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240006, description: "WU_E_TOOMANYRANGES - Too many byte ranges requested", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240007, description: "WU_E_INVALIDINDEX - Invalid index into the update list", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240008, description: "WU_E_ITEMNOTFOUND - The key for the item queried could not be found", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240009, description: "WU_E_OPERATIONINPROGRESS - Another conflicting operation was in progress", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024000A, description: "WU_E_COULDNOTCANCEL - Cancellation of the operation was not allowed", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024000B, description: "WU_E_CALL_CANCELLED - Operation was cancelled", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024000C, description: "WU_E_NOOP - No operation was required", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024000D, description: "WU_E_XML_MISSINGDATA - XML is missing required data", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024000E, description: "WU_E_XML_INVALID - XML is not valid", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024000F, description: "WU_E_CYCLE_DETECTED - Circular update relationships were detected", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240010, description: "WU_E_TOO_DEEP_RELATION - Update relationships too deep to evaluate", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240011, description: "WU_E_INVALID_RELATIONSHIP - Invalid update relationship", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240012, description: "WU_E_REG_VALUE_INVALID - Invalid registry value", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240013, description: "WU_E_DUPLICATE_ITEM - Duplicate item in list", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240016, description: "WU_E_INSTALL_NOT_ALLOWED - Install not allowed", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240017, description: "WU_E_NOT_APPLICABLE - The update is not applicable to this computer", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240018, description: "WU_E_NO_USERTOKEN - Failed to use the BITS service", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240019, description: "WU_E_EXCLUSIVE_INSTALL_CONFLICT - An exclusive update cannot be installed with other updates", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024001A, description: "WU_E_POLICY_NOT_SET - A policy value was not set", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024001B, description: "WU_E_SELFUPDATE_IN_PROGRESS - Self-update in progress", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024001D, description: "WU_E_INVALID_UPDATE - An update contains invalid metadata", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024001E, description: "WU_E_SERVICE_STOP - Service stop required", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024001F, description: "WU_E_NO_CONNECTION - No network connection was available", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240020, description: "WU_E_NO_INTERACTIVE_USER - Operation cannot continue without user interaction", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240021, description: "WU_E_TIME_OUT - Operation did not complete because it timed out", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240022, description: "WU_E_ALL_UPDATES_FAILED - Operation failed for all updates", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240024, description: "WU_E_NO_UPDATE - There are no updates", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240025, description: "WU_E_USER_ACCESS_DISABLED - Group policy has disabled user access", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240026, description: "WU_E_INVALID_UPDATE_TYPE - The type of update is invalid", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240027, description: "WU_E_URL_TOO_LONG - The URL exceeded the maximum length", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240028, description: "WU_E_UNINSTALL_NOT_ALLOWED - The update could not be uninstalled", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240029, description: "WU_E_INVALID_PRODUCT_LICENSE - Search may have missed some updates due to expired product license", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024002A, description: "WU_E_MISSING_HANDLER - A component required to detect updates was missing", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024002B, description: "WU_E_LEGACYSERVER - An operation did not complete because it requires a newer version of server", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024002C, description: "WU_E_BIN_SOURCE_ABSENT - A delta-compressed update could not be installed because it required the source", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024002D, description: "WU_E_SOURCE_ABSENT - A full-file update could not be installed because it required the source", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024002E, description: "WU_E_WU_DISABLED - Access to an unmanaged server is not allowed", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024002F, description: "WU_E_CALL_CANCELLED_BY_POLICY - Operation did not complete because DisableWindowsUpdateAccess policy was set", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240030, description: "WU_E_INVALID_PROXY_SERVER - The format of the proxy list was invalid", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240031, description: "WU_E_INVALID_FILE - The file is in the wrong format", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240032, description: "WU_E_INVALID_CRITERIA - The search criteria string was invalid", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240033, description: "WU_E_EULA_UNAVAILABLE - License terms could not be downloaded", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240035, description: "WU_E_UPDATE_NOT_PROCESSED - The update was not processed", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240036, description: "WU_E_INVALID_OPERATION - The objects current state does not allow the operation", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240037, description: "WU_E_NOT_SUPPORTED - The functionality is not supported", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240038, description: "WU_E_WINHTTP_INVALID_FILE - The downloaded file has an unexpected content type", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240039, description: "WU_E_TOO_MANY_RESYNC - Agent is asked by server to resync too many times", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240040, description: "WU_E_NO_SERVER_CORE_SUPPORT - WUA API method does not run on Server Core installation", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240041, description: "WU_E_SYSPREP_IN_PROGRESS - Service is not available while sysprep is running", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240042, description: "WU_E_UNKNOWN_SERVICE - The update service is no longer registered with AU", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240043, description: "WU_E_NO_UI_SUPPORT - There is no support for WUA UI", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240044, description: "WU_E_PER_MACHINE_UPDATE_ACCESS_DENIED - Only administrators can perform this operation on per-machine updates", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240FFF, description: "WU_E_UNEXPECTED - An operation failed due to reasons not covered by another error code", category: ErrorCategory::WindowsUpdate },
    // WU download/install manager errors
    ErrorCode { code: 0x80242000, description: "WU_E_UH_REMOTEUNAVAILABLE - A request for a remote update handler could not be completed", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80242002, description: "WU_E_UH_UNEXPECTEDCBSRESPONSE - The update handler received an unexpected response from CBS", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80242005, description: "WU_E_UH_WRONGHANDLER - The wrong update handler was called", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80242006, description: "WU_E_UH_INVALIDMETADATA - The update handler metadata is invalid", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80242007, description: "WU_E_UH_INSTALLERHUNG - An operation could not be completed because the installer exceeded the time limit", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80242008, description: "WU_E_UH_OPERATIONCANCELLED - An operation being done by the update handler was cancelled", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80242009, description: "WU_E_UH_BADHANDLERXML - The handler metadata XML is invalid", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024200B, description: "WU_E_UH_INSTALLERFAILURE - The update handler failed to install the update", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024200C, description: "WU_E_UH_FALLBACKTOSELFCONTAINED - The update handler should download self-contained content", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024200D, description: "WU_E_UH_NEEDANOTHERDOWNLOAD - The update handler needs to download a different payload", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024200E, description: "WU_E_UH_NOTIFYFAILURE - Update handler notification failure", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80243001, description: "WU_E_INSTALLATION_RESULTS_UNKNOWN_VERSION - Unknown version of installation results", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80243002, description: "WU_E_INSTALLATION_RESULTS_INVALID_DATA - Invalid data in installation results", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80243003, description: "WU_E_INSTALLATION_RESULTS_NOT_FOUND - Installation results not found", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80243FFD, description: "WU_E_NON_UI_MODE - Unable to show UI when in non-UI mode", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80243FFE, description: "WU_E_WUCLTUI_UNSUPPORTED_VERSION - Unsupported version of WU client UI", category: ErrorCategory::WindowsUpdate },
    // WUA SOAP/HTTP errors
    ErrorCode { code: 0x80244000, description: "WU_E_PT_SOAPCLIENT_BASE - SOAPCLIENT_ERRORs base", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80244001, description: "WU_E_PT_SOAPCLIENT_INITIALIZE - SOAP client initialization failed", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80244002, description: "WU_E_PT_SOAPCLIENT_OUTOFMEMORY - SOAP client out of memory", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80244004, description: "WU_E_PT_SOAPCLIENT_CONNECT - Cannot connect to the server", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80244005, description: "WU_E_PT_SOAPCLIENT_SEND - SOAP message could not be sent", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80244006, description: "WU_E_PT_SOAPCLIENT_SERVER - Server error", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80244007, description: "WU_E_PT_SOAPCLIENT_SOAPFAULT - SOAP fault", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80244010, description: "WU_E_PT_EXCEEDED_MAX_SERVER_TRIPS - The number of round trips to the server exceeded the maximum limit", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80244016, description: "WU_E_PT_HTTP_STATUS_BAD_REQUEST - HTTP 400 - Bad request", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80244017, description: "WU_E_PT_HTTP_STATUS_DENIED - HTTP 401 - Unauthorized", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80244018, description: "WU_E_PT_HTTP_STATUS_FORBIDDEN - HTTP 403 - Forbidden", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80244019, description: "WU_E_PT_HTTP_STATUS_NOT_FOUND - HTTP 404 - Not found", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024401B, description: "WU_E_PT_HTTP_STATUS_PROXY_AUTH_REQ - HTTP 407 - Proxy auth required", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024401C, description: "WU_E_PT_HTTP_STATUS_REQUEST_TIMEOUT - HTTP 408 - Request timeout", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80244022, description: "WU_E_PT_HTTP_STATUS_SERVICE_UNAVAIL - HTTP 503 - Service unavailable", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024402C, description: "WU_E_PT_WINHTTP_NAME_NOT_RESOLVED - WinHTTP name not resolved", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80244FFF, description: "WU_E_PT_UNEXPECTED - Communication error not covered by another WU_E_PT code", category: ErrorCategory::WindowsUpdate },
    // WUA Automatic Updates
    ErrorCode { code: 0x8024A000, description: "WU_E_AU_NOSERVICE - Automatic Updates was unable to service incoming requests", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024A002, description: "WU_E_AU_NONLEGACYSERVER - The old version of the Automatic Updates client has stopped because the WSUS server has been upgraded", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024A003, description: "WU_E_AU_LEGACYCLIENTDISABLED - The old version of the Automatic Updates client was disabled", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024A004, description: "WU_E_AU_PAUSED - Automatic Updates was unable to process incoming requests because it was paused", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024A005, description: "WU_E_AU_NO_REGISTERED_SERVICE - No unmanaged service is registered with AU", category: ErrorCategory::WindowsUpdate },
    // WU CBS (Component-Based Servicing) errors
    ErrorCode { code: 0x80245001, description: "WU_E_REDIRECTOR_LOAD_XML - The redirector XML document could not be loaded", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80245002, description: "WU_E_REDIRECTOR_S_FALSE - The redirector XML document is missing some required information", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80245003, description: "WU_E_REDIRECTOR_ID_SMALLER - The redirectorId in the downloaded redirector cab is less than in the cached cab", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80246001, description: "WU_E_DM_URLNOTAVAILABLE - A download manager operation could not be completed because the requested file does not have a URL", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80246002, description: "WU_E_DM_INCORRECTFILEHASH - A download manager operation could not be completed because the file digest was not recognized", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80246003, description: "WU_E_DM_UNKNOWNALGORITHM - A download manager operation could not be completed because the file metadata requested an unrecognized hash algorithm", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80246005, description: "WU_E_DM_NONETWORK - A download manager operation could not be completed because the network connection was unavailable", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80246008, description: "WU_E_DM_FAILTOCONNECTTOBITS - A download manager operation failed because the download manager was unable to connect the Background Intelligent Transfer Service", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80248000, description: "WU_E_DS_SHUTDOWN - An operation failed because Windows Update Agent is shutting down", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80248001, description: "WU_E_DS_INUSE - An operation failed because the data store was in use", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80248002, description: "WU_E_DS_INVALID - The current and expected states of the data store do not match", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80248003, description: "WU_E_DS_TABLEMISSING - The data store is missing a table", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80248004, description: "WU_E_DS_TABLEINCORRECT - The data store contains a table with unexpected columns", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80248005, description: "WU_E_DS_INVALIDTABLENAME - A table could not be opened because the table is not in the data store", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80248007, description: "WU_E_DS_NODATA - The information requested is not in the data store", category: ErrorCategory::WindowsUpdate },

    // ==========================================
    // BITS (Background Intelligent Transfer Service)
    // ==========================================
    ErrorCode { code: 0x80200001, description: "BG_E_NOT_FOUND - The requested job was not found", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200002, description: "BG_E_INVALID_STATE - The requested action is not allowed in the current job state", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200003, description: "BG_E_EMPTY - The job is empty", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200004, description: "BG_E_FILE_NOT_AVAILABLE - The file is not available", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200005, description: "BG_E_FILE_NOT_AVAILABLE - A file in the job is not available", category: ErrorCategory::Bits },
    ErrorCode { code: 0x8020000A, description: "BG_E_TOO_MANY_FILES - No more files can be added to this job", category: ErrorCategory::Bits },
    ErrorCode { code: 0x8020000B, description: "BG_E_LOCAL_FILE_CHANGED - Local file changed during transfer", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200010, description: "BG_E_NETWORK_DISCONNECTED - BITS is unable to contact the server", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200011, description: "BG_E_STRING_TOO_LONG - A string parameter was too long", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200013, description: "BG_E_INSUFFICIENT_HTTP_SUPPORT - The server does not support the necessary HTTP protocol", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200014, description: "BG_E_INSUFFICIENT_RANGE_SUPPORT - The server does not support the necessary HTTP byte range", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200015, description: "BG_E_ERROR_INFORMATION_UNAVAILABLE - Error information is not available", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200016, description: "BG_E_NETWORK_DISCONNECTED - Network disconnected", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200017, description: "BG_E_MISSING_FILE_SIZE - Server did not return the file size", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200018, description: "BG_E_INSUFFICIENT_HTTP_SUPPORT - Server does not support HTTP features required for BITS", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200019, description: "BG_E_INSUFFICIENT_RANGE_SUPPORT - Server does not support the necessary range protocol", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200020, description: "BG_E_CONNECTION_CLOSED - Connection was closed because of a redirect", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200022, description: "BG_E_HTTP_ERROR_403 - The server requires HTTP authentication", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200023, description: "BG_E_HTTP_ERROR_403 - HTTP 403 Forbidden", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200024, description: "BG_E_HTTP_ERROR_404 - HTTP 404 Not Found", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200025, description: "BG_E_HTTP_ERROR_407 - HTTP 407 Proxy Authentication Required", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200049, description: "BG_E_HTTP_ERROR_503 - HTTP 503 Service Unavailable", category: ErrorCategory::Bits },

    // ==========================================
    // ConfigMgr / SCCM
    // ==========================================
    ErrorCode { code: 0x80040600, description: "CCM_E_CONTENT_NOT_FOUND - Content not found on distribution point", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040601, description: "CCM_E_BAD_SITE_CODE - Invalid site code", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040602, description: "CCM_E_NOT_CONNECTED - Not connected to management point", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040690, description: "CCM_E_NO_MANAGEMENT_POINT - Could not discover management point", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040692, description: "CCM_E_TIMEOUT - CCM operation timed out", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040693, description: "CCM_E_LOW_WUA_VERSION - Low WUA version", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040700, description: "E_UPDDEPLOY_APPLY_NOT_ALLOWED - Install not allowed", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040701, description: "E_UPDDEPLOY_DOWNLOAD_NOT_ALLOWED - Download not allowed", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040702, description: "E_ASSIGNMENT_POLICY_NOT_FOUND - Assignment policy not available", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040703, description: "E_ANOTHER_JOB_IN_PROGRESS - Only one job is allowed at a time", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040704, description: "E_HARDREBOOT_PENDING - Hard reboot pending", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040708, description: "E_UPDDEPLOY_APPLY_NOT_REQUIRED - Software Updates install not required", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80041001, description: "WMI_E_FAILED - WMI generic failure", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80041002, description: "WMI_E_NOT_FOUND - WMI object not found", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80041003, description: "WMI_E_ACCESS_DENIED - WMI access denied", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80041006, description: "WMI_E_OUT_OF_MEMORY - WMI out of memory", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80041007, description: "SCCM_E_DEPENDENCYNOTMET - Dependency not met", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80041010, description: "SCCM_E_INVALIDPROPERTY - Invalid property", category: ErrorCategory::ConfigMgr },

    // ==========================================
    // Delivery Optimization
    // ==========================================
    ErrorCode { code: 0x80D01001, description: "DO_E_DOWNLOAD_NOT_FOUND - Download not found", category: ErrorCategory::DeliveryOpt },
    ErrorCode { code: 0x80D02002, description: "DO_E_DOWNLOAD_CANCELLED - Download was cancelled", category: ErrorCategory::DeliveryOpt },
    ErrorCode { code: 0x80D02003, description: "DO_E_UNKNOWN_PROPERTY_ID - Unknown property ID", category: ErrorCategory::DeliveryOpt },
    ErrorCode { code: 0x80D02004, description: "DO_E_READ_ONLY_PROPERTY - Property is read-only", category: ErrorCategory::DeliveryOpt },
    ErrorCode { code: 0x80D02005, description: "DO_E_NO_DOWNLOAD_SOURCES - No download sources available", category: ErrorCategory::DeliveryOpt },
    ErrorCode { code: 0x80D02011, description: "DO_E_BLOCKED_BY_COST_TRANSFER_POLICY - Download blocked by cost transfer policy", category: ErrorCategory::DeliveryOpt },
    ErrorCode { code: 0x80D06005, description: "DO_E_BLOCKED_BY_POLICY - Download blocked by policy", category: ErrorCategory::DeliveryOpt },
    ErrorCode { code: 0x80D06802, description: "DO_E_BLOCKED_BY_NO_NETWORK - Download blocked because there is no network", category: ErrorCategory::DeliveryOpt },

    // ==========================================
    // App Install — MSI exit codes
    // ==========================================
    ErrorCode { code: 1601, description: "ERROR_INSTALL_SERVICE_FAILURE - The Windows Installer service could not be accessed", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1602, description: "ERROR_INSTALL_USEREXIT - The user cancels installation", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1603, description: "ERROR_INSTALL_FAILURE - Fatal error occurred during installation", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1604, description: "ERROR_INSTALL_SUSPEND - Installation suspended, incomplete", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1605, description: "ERROR_UNKNOWN_PRODUCT - This action is only valid for products that are currently installed", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1606, description: "ERROR_UNKNOWN_FEATURE - Feature ID not registered", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1607, description: "ERROR_UNKNOWN_COMPONENT - Component ID not registered", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1608, description: "ERROR_UNKNOWN_PROPERTY - This is an unknown property", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1609, description: "ERROR_INVALID_HANDLE_STATE - Handle is in an invalid state", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1610, description: "ERROR_BAD_CONFIGURATION - The configuration data for this product is corrupt", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1612, description: "ERROR_INSTALL_SOURCE_ABSENT - The installation source for this product is not available", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1613, description: "ERROR_INSTALL_PACKAGE_VERSION - This installation package cannot be installed by the Windows Installer service", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1618, description: "ERROR_INSTALL_ALREADY_RUNNING - Another installation is already in progress", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1619, description: "ERROR_INSTALL_PACKAGE_OPEN_FAILED - This installation package could not be opened", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1620, description: "ERROR_INSTALL_PACKAGE_INVALID - This installation package could not be opened (invalid package)", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1621, description: "ERROR_INSTALL_UI_FAILURE - There was an error starting the Windows Installer service user interface", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1622, description: "ERROR_INSTALL_LOG_FAILURE - Error opening installation log file", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1623, description: "ERROR_INSTALL_LANGUAGE_UNSUPPORTED - This language of this installation package is not supported by your system", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1624, description: "ERROR_INSTALL_TRANSFORM_FAILURE - Error applying transforms", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1625, description: "ERROR_INSTALL_PACKAGE_REJECTED - This installation is forbidden by system policy", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1626, description: "ERROR_FUNCTION_NOT_CALLED - Function could not be executed", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1627, description: "ERROR_FUNCTION_FAILED - Function failed during execution", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1628, description: "ERROR_INVALID_TABLE - Invalid or unknown table specified", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1629, description: "ERROR_DATATYPE_MISMATCH - Data supplied is of wrong type", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1630, description: "ERROR_UNSUPPORTED_TYPE - Data of this type is not supported", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1631, description: "ERROR_CREATE_FAILED - The Windows Installer service failed to start", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1632, description: "ERROR_INSTALL_TEMP_UNWRITABLE - The Temp folder is either full or inaccessible", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1633, description: "ERROR_INSTALL_PLATFORM_UNSUPPORTED - This installation package is not supported on this platform", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1635, description: "ERROR_PATCH_PACKAGE_OPEN_FAILED - This patch package could not be opened", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1636, description: "ERROR_PATCH_PACKAGE_INVALID - This patch package could not be opened (invalid)", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1637, description: "ERROR_PATCH_PACKAGE_UNSUPPORTED - This patch package cannot be processed by the Windows Installer service", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1638, description: "ERROR_PRODUCT_VERSION - Another version of this product is already installed", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1639, description: "ERROR_INVALID_COMMAND_LINE - Invalid command line argument", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1640, description: "ERROR_INSTALL_REMOTE_DISALLOWED - Only administrators have permission to add, remove, or configure server software during a Terminal Services remote session", category: ErrorCategory::AppInstall },
    ErrorCode { code: 1641, description: "ERROR_SUCCESS_REBOOT_INITIATED - The requested operation completed successfully. The system will be restarted", category: ErrorCategory::AppInstall },
    ErrorCode { code: 3010, description: "ERROR_SUCCESS_REBOOT_REQUIRED - A restart is required to complete the install", category: ErrorCategory::AppInstall },
    // PSADT exit codes
    ErrorCode { code: 60001, description: "PSADT_GENERAL_FAILURE - PSADT general failure", category: ErrorCategory::AppInstall },
    ErrorCode { code: 60002, description: "PSADT_MISSING_FILE - PSADT missing file", category: ErrorCategory::AppInstall },
    ErrorCode { code: 60003, description: "PSADT_REQUIRES_ADMIN - PSADT requires admin but not elevated", category: ErrorCategory::AppInstall },
    ErrorCode { code: 60004, description: "PSADT_FAILED_LOAD_ASSEMBLY - PSADT failed to load assembly", category: ErrorCategory::AppInstall },
    ErrorCode { code: 60005, description: "PSADT_DISPLAY_ERROR - PSADT error displaying installation prompt", category: ErrorCategory::AppInstall },
    ErrorCode { code: 60007, description: "PSADT_EXPORT_TASK_FAILED - PSADT failed to export scheduled task XML", category: ErrorCategory::AppInstall },
    ErrorCode { code: 60008, description: "PSADT_MODULE_LOAD_FAILED - PSADT module failed to load", category: ErrorCategory::AppInstall },
    ErrorCode { code: 60009, description: "PSADT_NO_USER - PSADT no logged-on user detected", category: ErrorCategory::AppInstall },
    ErrorCode { code: 60012, description: "PSADT_USER_DEFERRED - PSADT user selected defer/postpone", category: ErrorCategory::AppInstall },
    ErrorCode { code: 70001, description: "PSADT_USER_DECLINED - PSADT user selected No when prompted to close app", category: ErrorCategory::AppInstall },
    // HRESULT-wrapped MSI/AppInstall errors (from original DB)
    ErrorCode { code: 0x80070641, description: "ERROR_INSTALL_SERVICE_FAILURE - The Windows Installer Service could not be accessed", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80070642, description: "ERROR_INSTALL_USEREXIT - User cancelled installation", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80070644, description: "ERROR_INSTALL_SUSPEND - Installation suspended", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80070645, description: "ERROR_UNKNOWN_PRODUCT - Unknown product", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80070660, description: "ERROR_INSTALL_REMOTE_DISALLOWED - Remote installations are not allowed", category: ErrorCategory::AppInstall },
    // MSIX/AppX errors
    ErrorCode { code: 0x80073CF0, description: "ERROR_INSTALL_OPEN_PACKAGE_FAILED - The package could not be opened", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80073CF3, description: "ERROR_INSTALL_RESOLVE_DEPENDENCY_FAILED - Package failed dependency validation", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80073CF6, description: "ERROR_INSTALL_OUT_OF_DISK_SPACE - Not enough disk space for package", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80073CF9, description: "ERROR_INSTALL_CANCEL - Package installation was canceled", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80073CFB, description: "ERROR_INSTALL_FAILED - Package already installed, reinstallation blocked", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80073CFF, description: "ERROR_INSTALL_POLICY_FAILURE - To install this app, sideloading must be enabled", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80073D02, description: "ERROR_INSTALL_PREREQUISITE_FAILED - Package prerequisites not met", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80073D06, description: "ERROR_PACKAGES_IN_USE - Package in use, cannot update", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80073D0A, description: "ERROR_DEPLOYMENT_BLOCKED_BY_POLICY - Deployment blocked by policy", category: ErrorCategory::AppInstall },
    // WinGet
    ErrorCode { code: 0x8A150001, description: "APPINSTALLER_CLI_ERROR_INTERNAL - Internal error", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x8A150002, description: "APPINSTALLER_CLI_ERROR_INVALID_CL - Invalid command line", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x8A150003, description: "APPINSTALLER_CLI_ERROR_COMMAND_FAILED - Command failed", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x8A150014, description: "APPINSTALLER_CLI_ERROR_NO_APPLICABLE_INSTALLER - No applicable installer found", category: ErrorCategory::AppInstall },

    // ==========================================
    // Certificate errors
    // ==========================================
    ErrorCode { code: 0x800B0001, description: "TRUST_E_PROVIDER_UNKNOWN - Unknown trust provider", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B0003, description: "TRUST_E_SUBJECT_FORM_UNKNOWN - Unknown form type", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B0004, description: "TRUST_E_SUBJECT_NOT_TRUSTED - The subject is not trusted for the specified action", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B0100, description: "TRUST_E_NOSIGNATURE - No signature was present in the subject", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B0101, description: "CERT_E_EXPIRED - A required certificate is not within its validity period", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B0106, description: "CERT_E_CHAINING - Could not form a valid certificate chain", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B0109, description: "CERT_E_UNTRUSTEDROOT - A certificate chain processed but terminated in a root certificate not trusted", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B010A, description: "CERT_E_CHAINING - A certificate chain could not be built to a trusted root authority", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B010B, description: "CERT_E_REVOCATION_FAILURE - The revocation process could not continue", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B010C, description: "CERT_E_CN_NO_MATCH - The certificate CN name does not match the passed value", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B010D, description: "CERT_E_WRONG_USAGE - The certificate is not valid for the requested usage", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B0110, description: "CERT_E_CRITICAL - A certificate contains an unknown extension that is marked critical", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B0111, description: "CERT_E_PURPOSE - The certificate is being used for a purpose other than the ones specified by the CA", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B0113, description: "CERT_E_MALFORMED - A certificate is missing or has an empty value for an important field", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B0114, description: "CERT_E_UNTRUSTEDCA - A certification chain processed correctly but one of the CA certificates is not trusted by the policy provider", category: ErrorCategory::Certificate },

    // ==========================================
    // Intune / MDM
    // ==========================================
    ErrorCode { code: 0x87D00215, description: "INTUNEWIN_E_INSTALL_FAILURE - The application installation failed", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D00324, description: "INTUNEWIN_E_DETECTION_FAILED - Post-install detection failed", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D00607, description: "INTUNEWIN_E_DOWNLOAD_FAILED - Content download failed", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D01101, description: "INTUNEWIN_E_TIMEOUT - Application install timed out", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D10001, description: "INTUNE_CLIENT_ERROR - Intune client error", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D1041C, description: "INTUNE_NOT_DETECTED_POST_INSTALL - Application was not detected after installation completed", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D11388, description: "INTUNE_IOS_BUSY - iOS device is currently busy", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D1313C, description: "INTUNE_NETWORK_LOST - Network connection on the client was lost during download", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D13B64, description: "INTUNE_IOS_INSTALL_FAILURE - iOS app installation failure", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D13B66, description: "INTUNE_APP_EXPIRED - App is managed but has expired or been removed by user", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D13B9B, description: "INTUNE_RETRY_NEXT_SYNC - App installation failed, Intune will retry next sync", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D30000, description: "INTUNE_UNKNOWN - Unknown error (last step succeeded but current step has no defined output)", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D30001, description: "INTUNE_NOT_DETECTED_AFTER_INSTALL - App was not detected after installation", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D30003, description: "INTUNE_REBOOT_REQUIRED - App install requires device reboot", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D30004, description: "INTUNE_UNINSTALLED_AFTER_DETECT - App was uninstalled after being detected", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D30006, description: "INTUNE_DETECTION_FAILED - App was installed but detection check failed", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D30065, description: "INTUNE_CONTENT_INFO_FAILED - Failed to retrieve content information", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D30067, description: "INTUNE_UNZIP_FAILED - Error unzipping downloaded content", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D30068, description: "INTUNE_DOWNLOAD_FAILED - Error downloading content", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D3006A, description: "INTUNE_DOWNLOAD_TIMEOUT - Content download timed out", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D300C8, description: "INTUNE_INSTALL_PENDING - App install not yet complete", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D300CA, description: "INTUNE_ENFORCEMENT_FAILED - Failed to enforce app", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D300CC, description: "INTUNE_OOBE_SKIPPED - Device in OOBE, skipping", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D300CE, description: "INTUNE_NOT_APPLICABLE - App not applicable to device", category: ErrorCategory::Intune },

    // ==========================================
    // Network — WinHTTP errors
    // ==========================================
    ErrorCode { code: 0x80072EE1, description: "ERROR_WINHTTP_OUT_OF_HANDLES - No more handles could be generated", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072EE2, description: "ERROR_WINHTTP_TIMEOUT - The request has timed out", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072EE4, description: "ERROR_WINHTTP_INTERNAL_ERROR - An internal error has occurred", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072EE5, description: "ERROR_WINHTTP_INVALID_URL - The URL is invalid", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072EE7, description: "ERROR_WINHTTP_NAME_NOT_RESOLVED - The server name could not be resolved", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072EFD, description: "ERROR_WINHTTP_CANNOT_CONNECT - Connection to the server failed", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072EFE, description: "ERROR_WINHTTP_CONNECTION_ERROR - The connection with the server has been reset or terminated", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072F06, description: "ERROR_WINHTTP_SECURE_CERT_DATE_INVALID - SSL certificate date is invalid", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072F0C, description: "ERROR_WINHTTP_CLIENT_AUTH_CERT_NEEDED - The server requires SSL client authentication", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072F0D, description: "ERROR_WINHTTP_INVALID_CA - Invalid CA certificate", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072F76, description: "ERROR_WINHTTP_HEADER_NOT_FOUND - The requested header could not be located", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072F78, description: "ERROR_WINHTTP_INVALID_SERVER_RESPONSE - The server response could not be parsed", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072F89, description: "ERROR_WINHTTP_SECURE_CERT_REVOKED - SSL certificate revoked", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072F8A, description: "ERROR_WINHTTP_SECURE_CERT_CN_INVALID - SSL certificate common name does not match", category: ErrorCategory::Network },
    ErrorCode { code: 0x80072F8F, description: "ERROR_WINHTTP_SECURE_FAILURE - One or more SSL errors were encountered", category: ErrorCategory::Network },

    // ==========================================
    // Security — Crypto / SSPI
    // ==========================================
    ErrorCode { code: 0x80090001, description: "NTE_BAD_UID - Bad UID", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090002, description: "NTE_BAD_HASH - Bad hash", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090003, description: "NTE_BAD_KEY - Bad key", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090005, description: "NTE_BAD_DATA - Bad data", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090006, description: "NTE_BAD_SIGNATURE - Invalid signature", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090010, description: "NTE_PROV_TYPE_NOT_DEF - Provider type not defined", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090020, description: "NTE_INTERNAL_ERROR - Internal error", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090300, description: "SEC_E_INSUFFICIENT_MEMORY - Not enough memory available to complete the request", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090302, description: "SEC_E_INVALID_HANDLE - The handle specified is invalid", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090304, description: "SEC_E_LOGON_DENIED - The logon attempt failed", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090308, description: "SEC_E_INVALID_TOKEN - The token supplied to the function is invalid", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090311, description: "SEC_E_NO_AUTHENTICATING_AUTHORITY - No authority could be contacted for authentication", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090317, description: "SEC_E_CERT_EXPIRED - The received certificate has expired", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090322, description: "SEC_E_WRONG_PRINCIPAL - The target principal name is incorrect", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090325, description: "SEC_E_UNTRUSTED_ROOT - The certificate chain was issued by an authority that is not trusted", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090326, description: "SEC_E_REVOCATION_OFFLINE - The revocation function was unable to check revocation because the revocation server was offline", category: ErrorCategory::Security },
    ErrorCode { code: 0x80090331, description: "SEC_E_ALGORITHM_MISMATCH - The client and server cannot communicate because they do not possess a common algorithm", category: ErrorCategory::Security },
];
